## #ddev-generated

providers:
  openai:
    name: "OpenAI"
    description: "GPT-4, GPT-3.5, DALL-E, Embeddings"
    required_vars:
      - OPENAI_API_KEY
    optional_vars:
      OPENAI_MODEL: "gpt-4"
      OPENAI_BASE_URL: "https://api.openai.com/v1"
    capabilities: ["text-generation", "embeddings", "image-generation"]
    dependencies: []

  anthropic:
    name: "Anthropic"
    description: "Claude 3.5, Claude 3"
    required_vars:
      - ANTHROPIC_API_KEY
    optional_vars:
      ANTHROPIC_MODEL: "claude-3-5-sonnet-20241022"
      ANTHROPIC_BASE_URL: "https://api.anthropic.com"
    capabilities: ["text-generation"]
    dependencies: []

  ollama:
    name: "Ollama (Local)"
    description: "Self-hosted LLMs (Llama, Mistral, etc.)"
    required_vars: []
    optional_vars:
      OLLAMA_MODEL: "llama3"
      OLLAMA_HOST: "http://ollama:11434"
    capabilities: ["text-generation", "embeddings"]
    dependencies: ["ollama-service"]

  google_gemini:
    name: "Google Gemini"
    description: "Gemini Pro, Gemini Vision"
    required_vars:
      - GOOGLE_API_KEY
    optional_vars:
      GOOGLE_MODEL: "gemini-pro"
    capabilities: ["text-generation", "image-analysis"]
    dependencies: []
